// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var v0 = {
  x: 3
};

var v1 = {
  x: 3
};

var v2 = {
  x: 3,
  y: 4
};

exports.v0 = v0;
exports.v1 = v1;
exports.v2 = v2;
/* No side effect */
