// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


process.on("exit", (function (exitCode) {
        console.log("error code: " + exitCode.toString());
        
      }));

process.on("exit", (function (exitCode) {
        console.log("error code: " + exitCode.toString());
        
      }));

var exit = "exit";

exports.exit = exit;
/*  Not a pure module */
